### ISSUE TITLE
How to implement source codes for one item

### ISSUE THREAD

**Issue by haydarKarkin** [Vkt0r/AccordionMenu#1]
Hello,

How can i implement your source codes for just one subitem?

Thank you

**Comment by Vkt0r** [comment]
Hi, 

If you want to use just one subitem then you need to modify in the `viewDidLoad` the fill of the items like in the following way:

    for (var i = 0; i < 10; i++) {
            topItems.append("Item \(i + 1)")
            actualPositions.append(-1)
            
            var items = [String]()
 
            // You can change the number of elements here to 1 for example.
            for (var i = 0; i < 1; i++) {
                items.append("Subitem \(i)")
            }
            self.subItems.append(items)
     }

Note the comment in the code. 

I hope this help you.

**Comment by haydarKarkin** [comment]
Hi,

Thank you very much for your help.

Best regards
Haydar
