### ISSUE TITLE
Getting index..

### ISSUE THREAD

**Issue by htarwara6245** [Vkt0r/AccordionMenu#10]
Assume i expand Parent cell.So,how can i get the selected child cell index and parent cell index in code?

If you have anytime,can you post an example with realworld data,like below

[Smith Family]
->[Adem Smith]
->[Jason Smith]
[Luca Family]
->[Steven Luca]
->[James Luca]
->[Adem Luca]
->[Dean Luca]

#####Problem###### 
1.If i select luca,and steven,i want to get index of luca and james.
2.And setting initial data is not meet for my requirement which mean child will be dynamic
self.setInitialDataSource(numberOfRowParents: (Dynamic Parent Count), numberOfRowChildPerParent: (Dynamic Child Count for each Parent))

I am asking you this because the data will be come from the server and i need to fetch data from the model.
Any Help

**Comment by Vkt0r** [comment]
Hi @htarwara6245 !

In the readme I explained how you can get the index for the child and the parent cell when the cell is tapped, I going to update with a header in form of question to help everyone with your problem.

Every time you tap a cell the `didSelectRowAtIndexPath ` method is called, then when we call the method `findParent()` passing it as argument the selected `indexPath.row` returns everything we need to calculate the child index like in the following code:

    override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {

       let (parent, isParentCell, actualPosition) = self.findParent(indexPath.row)

       guard isParentCell else {
           NSLog("A child was tapped!!!")

           // The value of the child is indexPath.row - actualPosition - 1 
           NSLog("The value of the child is \(self.dataSource[parent].childs[indexPath.row - actualPosition - 1])")
           return
       }

       self.tableView.beginUpdates()
       self.updateCells(parent, index: indexPath.row)
       self.tableView.endUpdates()
    }

As you can see in the above code the index for the child tapped it's calculated in the following line:

    self.dataSource[parent].childs[indexPath.row - actualPosition - 1])

In the above line you can access to the data directly and the index for the parent it's the variable `parent` according to the originals positions if you want the index right now in the table view with another cells opened etc, it's the `indexPath.row`

I hope this help you. Let me know if I can help you in anything else.

**Comment by radiansys** [comment]
self.dataSource[parent].childs[indexPath.row - actualPosition - 1])

child is not accessible  due to internal protection level
