### ISSUE TITLE
How to close an expanded parent when clicked another parent?

### ISSUE THREAD

**Issue by tahaSuleyman** [Vkt0r/AccordionMenu#2]
Well I tried to do this but it seems a bit complicated to me. I just want to close an expanded parent when I click not expanded parent.

**Comment by tahaSuleyman** [comment]
I know that I have to edit these lines. I tried but I failed. All I need is if one expand the other collapses. 
`        self.tableView.beginUpdates()
        
        if let value = self.currentItemsExpanded.indexOf(self.findParent(indexPath.row)) {
            
            self.collapseSubItemsAtIndex(indexPath.row)
            self.actualPositions[parent] = -1
            self.currentItemsExpanded.removeAtIndex(value)
            
            for (var i = parent + 1; i < self.topItems.count; i++) {
                if self.actualPositions[i] != -1 {
                    self.actualPositions[i] -= self.subItems[parent].count
                }
            }
        }
        else {
            let parent = self.findParent(indexPath.row)
            
            self.expandItemAtIndex(indexPath.row)
            self.actualPositions[parent] = indexPath.row
            
            for (var i = parent + 1; i < self.topItems.count; i++) {
                if self.actualPositions[i] != -1 {
                    self.actualPositions[i] += self.subItems[parent].count
                }
            }
            self.currentItemsExpanded.append(parent)
        }
        
        self.tableView.endUpdates()`

**Comment by Vkt0r** [comment]
Let me think if I understand what you need it's only have a parent cell expanded always and in case of tap in another parent first close the expanded and tap again to expand the curretn parent cell?

**Comment by tahaSuleyman** [comment]
Yes kinda. If you click another parent cell expanded cell will collapse and clicked will expand.

**Comment by Vkt0r** [comment]
Taha I have update the project based in your needs, I think it was a good approach to have in the project allowing severals expanded rows or only one at time. You can have only one cell at time expanded setting the value for the variable `numberOfCellsExpanded` to the value `.One`. You can check out the new readme to understand better.
