### ISSUE TITLE
Get child value

### ISSUE THREAD

**Issue by vre142** [Vkt0r/AccordionMenu#4]
Hi,
I have a problem and question with this library. I want to get value of child how can i do it?

Thanks,
Vafa

**Comment by Vkt0r** [comment]
Hi, 

You can get the value for the child using the new update repo, I've added the inside the `guard` statement the calculation for the value of the child.

```swift
override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        
    let (parent, isParentCell, actualPosition) = self.findParent(indexPath.row)
    
    guard isParentCell else {
        NSLog("A child was tapped!!!")
        
        // The value of the child is indexPath.row - actualPosition - 1
        NSLog("The value of the child is \(self.dataSource[parent].childs[indexPath.row - actualPosition - 1])")
        
        return
    }
    
    self.tableView.beginUpdates()
    self.updateCells(parent, index: indexPath.row)
    self.tableView.endUpdates()
}
```

In the method `findParent(_:)` I return the position of the parent in the original data source, if it's a parent cell or not and it's position in the whole list with the expanded cells too, so we can calculate it subtracting the `indexPath.row` from the `actualPosition` and this give us the value inside the array of child.

I hope this can help you,
