### ISSUE TITLE
problem with my code and your library

### ISSUE THREAD

**Issue by vre142** [Vkt0r/AccordionMenu#5]
dear viktor, 
Thanks for your answer but i changed your code in my code like this and I can't use your update can you tell me what can i do for find subitem value with my code?

Thanks,

[SearchSection.swift.zip](https://github.com/Vkt0r/AccordionMenu/files/201308/SearchSection.swift.zip)

**Comment by Vkt0r** [comment]
@vre142 I saw you're using in  your code the old version of the library, please update to the last update to you can access it in a very easy way as I answer you in your last issue, using this part of the code you can get the value of the child tapped 

    override func tableView(tableView: UITableView, didSelectRowAtIndexPath indexPath: NSIndexPath) {
        
        let (parent, isParentCell, actualPosition) = self.findParent(indexPath.row)
        
        guard isParentCell else {
            NSLog("A child was tapped!!!")
            
            // The value of the child is indexPath.row - actualPosition - 1
            NSLog("The value of the child is \(self.dataSource[parent].childs[indexPath.row - actualPosition - 1])")
            
            return
        }
        
        self.tableView.beginUpdates()
        self.updateCells(parent, index: indexPath.row)
        self.tableView.endUpdates()
    }

I hope this help you
