### ISSUE TITLE
Can't form Range with end < start

### ISSUE THREAD

**Issue by 99xs** [Vkt0r/AccordionMenu#8]
Hi Vkt0r,

First of all thank you for this code. Just one issue so far.. In case child is empty, I get an error:
"Can't form Range with end < start"

I'm using it for generating a category menu. Some items have subcategories, some don't.

Any idea how I can change the code?

**Comment by Vkt0r** [comment]
@99xs You're welcome. Issue fixed, good catch!!! 👍 In case of not being child the range is malformed I mean the first is greater to the second, fixed with this line:

    guard index + 1 <= index + numberOfChilds else { return }

Avoiding runtime exceptions. Please update your repository with the new updates I've made.
