### ISSUE TITLE
dataSource

### ISSUE THREAD

**Issue by lukejones1** [Vkt0r/AccordionMenu#9]
private func setInitialDataSource(numberOfRowParents parents: Int, numberOfRowChildPerParent childs: Int) {
        
        // Set the total of cells initially.
        self.total = parents
        
        let data = [Parent](count: parents, repeatedValue: Parent(state: .Collapsed, childs: [String](), title: ""))
        
        **dataSource = data.enumerate().map({ (index: Int, element: Parent) -> Parent in**
            
            var newElement = element
            
            newElement.title = "Item \(index)"
            
            // generate the random number between 0...childs
            let random = Int(arc4random_uniform(UInt32(childs + 1))) + 1
            
            // create the array for each cell
            newElement.childs = (0..<random).enumerate().map {"Subitem \($0.index)"}
            
            return newElement
        })
    }

This is what i don't understand the most I guess, specifically the dataSource = data.enumerate()...

What I'm trying to do is implement it into my app, making the third row of my tableview expand with about 5-6 cells drop down once expanded.

**Comment by Vkt0r** [comment]
@lukejones1 Sure no problem. The aim of the `enumerate` is create a pair `(index, element)`, for example if iterate it over an array `[0,1,2]` you should see `(0,0), (1,1), (2,2)` as I mention above `(position, element)`. The I use the `map` function to return a new element of type `Parent` with the tuple of `(position, element)`.

Inside the `map` function I'm creating a random number of childs for every parent and in the following line:

   newElement.childs = (0..<random).enumerate().map {"Subitem \($0.index)"}

I used the `enumerate` as a for to assign numbers to the child's.

The way I use it's only to add a data source, it could be added too in another way using the `Parent` data type created to facilitate the way of do it.

I hope this help you.
